### ISSUE TITLE
can't mapping mssql  (sqlserver 13)

### ISSUE THREAD

**Issue by openkava** [neo4j-contrib/neo4j-etl#87]
java.sql.SQLException: No matching schemas found
        at org.neo4j.etl.sql.DatabaseClient.getCatalog(DatabaseClient.java:184)
        at org.neo4j.etl.sql.DatabaseCatalog.<init>(DatabaseCatalog.java:81)
        at org.neo4j.etl.sql.metadata.TableInfoAssembler.<init>(TableInfoAssembler.java:35)
        at org.neo4j.etl.commands.DatabaseInspector.buildSchemaExport(DatabaseInspector.java:35)
        at org.neo4j.etl.commands.rdbms.GenerateMetadataMapping.call(GenerateMetadataMapping.java:108)
        at org.neo4j.etl.commands.rdbms.GenerateMetadataMapping.call(GenerateMetadataMapping.java:29)
        at org.neo4j.etl.cli.rdbms.GenerateMetadataMappingCli.run(GenerateMetadataMappingCli.java:118)
        at org.neo4j.etl.util.CliRunner.run(CliRunner.java:42)
        at org.neo4j.etl.util.CliRunner.run(CliRunner.java:35)
        at org.neo4j.etl.NeoIntegrationCli.main(NeoIntegrationCli.java:43)
Caused by: schemacrawler.schemacrawler.SchemaCrawlerException: No matching schemas found
        at schemacrawler.crawl.SchemaCrawler.crawlSchemas(SchemaCrawler.java:406)
        at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:814)
        at schemacrawler.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:75)
        at org.neo4j.etl.sql.DatabaseClient.getCatalog(DatabaseClient.java:181)

**Comment by openkava** [comment]
- Skipping reading import options from file because file [] doesn't exist.
- Creating RDBMS to CSV mappings...
- Using database plugin for 
- Crawling schemas
- Retrieving all schemas
- Retrieving all catalogs
- Processed 13 rows for <retrieveAllSchemas>
- Retrieved 0 schemas
- Total time taken for <crawlSchemas> - 00:00:00.027 hours
-100.0% - 00:00:00.027 - <retrieveSchemas>
-  0.0% - 00:00:00.000 - <sortAndFilterSchemas>

- Command failed due to error (SQLException: No matching schemas found). Rerun with --debug flag for detailed diagnostic information
